# Generated by Django 3.2.16 on 2022-11-24 11:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('phno', models.IntegerField(null=True)),
                ('mail', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('acType', models.CharField(blank=True, max_length=50, null=True)),
                ('creditCard', models.BooleanField(default=False)),
                ('chequebook', models.BooleanField(default=False)),
                ('debitCard', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.branch')),
                ('dist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.district')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='dist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.district'),
        ),
    ]
