# Generated by Django 3.2.16 on 2022-11-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_auto_20221124_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='acType',
            field=models.CharField(choices=[('savingsAccount', 'Savings Account'), ('currentAccount', 'Current Account'), ('fixedAccount', 'Fixed Account')], default='savingsAccount', max_length=50),
        ),
    ]
