# Generated by Django 3.2.16 on 2022-11-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_data_actype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='chequebook',
        ),
        migrations.RemoveField(
            model_name='data',
            name='creditCard',
        ),
        migrations.RemoveField(
            model_name='data',
            name='debitCard',
        ),
        migrations.AddField(
            model_name='data',
            name='service',
            field=models.CharField(choices=[('creditCard', 'Credit Card'), ('debitCard', 'Debit Card'), ('chequeBook', 'Cheque Book')], default='creditCard', max_length=500),
        ),
    ]
