# Generated by Django 3.2.16 on 2022-11-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_auto_20221124_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='service',
            field=models.TextField(default='creditCard', max_length=500),
        ),
    ]
